language: python

python:
  - 2.6
  - 2.7

install:
  - pip install -Ur requirements.txt --allow-all-external --allow-unverified netifaces
  - pip install -Ur requirements-test.txt --allow-all-external

script: "py.test -vs --pep8 --cov upaas_client"
