#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    :copyright: Copyright 2013 by Łukasz Mierzwa
    :contact: l.mierzwa@gmail.com
"""


from upaas_client.main import ClientApplication
from upaas_client.register import Register
from upaas_client.list import List
from upaas_client.show import Show
from upaas_client.update import Update
from upaas_client.build import Build


if __name__ == "__main__":
    ClientApplication.run()
